application: ttupdater
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: /task/.*
  script: apps.task_app
  login: admin

- url: /manage/.*
  script: apps.manage_app
  login: admin

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version:  "2.6"
- name: lxml
  version:  "2.3.5"

builtins:
- remote_api: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
