application: ttupdater
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: /task/.*
  script: handlers.task_handler
  login: admin

- url: /manage/.*
  script: handlers.manage_handler
  login: admin

- url: /.*
  script: handlers.public_handler

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version:  "2.6"
- name: lxml
  version:  "2.3.5"

builtins:
- remote_api: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^Makefile
- ^requirements-.*